### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [flakanet/prj-rev-bwfs-dasmoto#6]
https://github.com/flakanet/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/Resources/CSS/index.css#L1-L31

This is not readable. Use indentation and whitespace (like in your HTML code) so that it's easy to read your code. Always strive for code readability, there's no benefit in writing one massive continuous block of code.

There's a lot of shared styles that you're repeating across your CSS rules. In addition to readability, you should keep your code as concise as possible so that it's maintainable and easy to update your website.

Since all of the elements on the page have the same font, you don't need to repeat that style every time. Just put it into a rule that selects each element.

```css
h1, h2, p, span {
  font-family: Helvetica;
}
```

Same for the styles that are being applied to each `h2` tag. You should just write them into a rule that selects each `h2`.

```css
h2 {
  font-size: 32%;
  font-weight: bold;
  color: white;
}
```
